services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/staticfiles:/app/staticfiles
      - /app/node_modules:/app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=calmmind.settings
    depends_on:
      - db
    command: daphne -b 0.0.0.0 -p 8000 calmmind.asgi:application
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  postgres_data: