# Generated by Django 5.1.4 on 2025-02-22 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHQ9Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('q6', models.PositiveSmallIntegerField()),
                ('q7', models.PositiveSmallIntegerField()),
                ('q8', models.PositiveSmallIntegerField()),
                ('q9', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('depression_level', models.CharField(choices=[('0', 'No Depression'), ('1', 'Low Depression'), ('2', 'Mild Depression'), ('3', 'Severe Depression')], max_length=1)),
                ('predicted_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('predicted_depression_level', models.CharField(blank=True, choices=[('0', 'No Depression'), ('1', 'Low Depression'), ('2', 'Mild Depression'), ('3', 'Severe Depression')], max_length=1, null=True)),
                ('assessment_date', models.DateField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient')),
            ],
        ),
    ]
