# Generated by Django 5.1.4 on 2025-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phq9assessment',
            name='depression_level',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Moderately Severe'), ('4', 'Severe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='phq9assessment',
            name='predicted_depression_level',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Moderately Severe'), ('4', 'Severe')], max_length=1, null=True),
        ),
    ]
