# Generated by Django 5.1.4 on 2024-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_doctor_patient_user_delete_test_db_patient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='visiting_hour',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
