# Generated by Django 5.1.4 on 2025-03-30 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('intent', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_chat_logs', to='auth_app.patient')),
            ],
        ),
    ]
